"""empty message

Revision ID: 89f9adbc53c6
Revises: e28d49e17967
Create Date: 2019-05-08 10:20:43.603173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f9adbc53c6'
down_revision = 'e28d49e17967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface_data', sa.Column('describe', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interface_data', 'describe')
    # ### end Alembic commands ###
