"""empty message

Revision ID: c613e2b8b785
Revises: 
Create Date: 2019-04-23 15:58:12.614120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c613e2b8b785'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('describe', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('describe', sa.String(length=256), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('interface_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('describe', sa.String(length=256), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('describe', sa.String(length=256), nullable=True),
    sa.Column('api_path', sa.String(length=64), nullable=True),
    sa.Column('api_method', sa.String(length=16), nullable=True),
    sa.Column('is_archive', sa.Boolean(), nullable=True),
    sa.Column('interface_collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interface_collection_id'], ['interface_collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('interface_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=True),
    sa.Column('api_parameters', sa.String(length=256), nullable=True),
    sa.Column('api_response', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interface_data')
    op.drop_table('interfaces')
    op.drop_table('interface_collections')
    op.drop_table('projects')
    op.drop_table('works')
    # ### end Alembic commands ###
