"""

Revision ID: e28d49e17967
Revises: c613e2b8b785
Create Date: 2019-04-29 14:34:18.127513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28d49e17967'
down_revision = 'c613e2b8b785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'state')
    # ### end Alembic commands ###
